yandex_token    = "y0_AgAAAAAB_hFpAATuwQAAAAD691h6AADMd1945zxKP4mTFMNp4Ujl-tx4zw"
cloud_id        = "b1grmqmee8dvnrrplc8d"
folder_id       = "b1gltk79jlvu4fu074l8"
ssh_public_key_path = "/mnt/c/Users/Micro/.ssh/id_rsa.pub"
user_name       = "microvolk"
sudo_password   = "Hjvfirf123"
