---
- name: Join Kubernetes Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Retrieve join command from master
      delegate_to: "{{ groups['master'][0] }}"  # Получаем первый хост из группы master
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Join worker to Kubernetes cluster
      shell: "{{ join_command.stdout }} --ignore-preflight-errors=all"
